name: Build compy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build compy
        run: |
          go get github.com/barnacs/compy
          cd go/src/github.com/barnacs/compy/
          go install
      - name: Move compy
        run: |
          mv go/bin/compy .
          upx --ultra-brute compy
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: compy
          push_options: '--force'
