name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build mitmdump
        run: |
          sudo apt-get update
          sudo apt-get install -y zlib1g-dev libjpeg-dev libwebp-dev upx
          CC="cc -mavx2" pip install --user pillow-simd --global-option="build_ext" --global-option="--enable-webp"
          pip install --user mitmdump
        env:
          PYTHONUSERBASE: ./__pypackages__
      - name: Building tailscale.combind
        run: |
          git clone -b v1.64.0 https://github.com/tailscale/tailscale.git ./tailscale-source
          cd tailscale-source
          build_dist.sh --extra-small
          go build -o ../tailscale.combined -tags ts_include_cli -ldflags="-s -w" -trimpath ./cmd/tailscaled
          cd ../
          upx --ultra-brute tailscale.combined
          ln -s tailscale.combined tailscale
          ln -s tailscale.combined tailscaled
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: tailscale tailscaled tailscale.combind __pypackages__