name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build mitmdump
        run: |
          sudo apt-get update
          sudo apt-get install libwebp-dev
          CC="cc -mavx2" pip install -U --force-reinstall pillow-simd --global-option="build_ext" --global-option="--enable-webp"
          pip install mitmdump
      - name: Build tailscale.combined
        run: |
          git clone https://github.com/tailscale/tailscale.git ./tailscale-source
          cd tailscale-source
          go build -o tailscale.combined -tags ts_include_cli -ldflags="-s -w" -trimpath ./cmd/tailscaled
          mv tailscale.combined ../
          cd ../
          upx --ultra-brute tailscale.combined
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: tailscale.combined $HOME/.local/lib/python3.10/site-packages
